
#General configuration
[general]

	[general.bot]
		#Discord Bot Token
		token = ""

#Channel configurations
[[channels]]
	id = 242318118340805120
	dimensions = [0]

	[channels.messages]
		started = "**Server started!** (took {ELAPSED|s.S's'}) :ok_hand:"
		stopping = "**Server stopping...** ({DATE|d/MM/yyyy '@' hh:mma}) :raised_hand:"
		stopped = "**Server stopped!** (after {UPTIME|d'd' H'hr' m'mins' s'secs'}) :no_entry:"
		crashed = "**Server crash detected!** (after {UPTIME|d'd' H'hr' m'mins' s'secs'}) :warning:"

[[channels]]
	id = 262311018300915141
	dimensions = [-1, 1]

	[channels.messages]
		started = "**Server started!** (@ {DATE|h:mma}) :ok_hand:"

