
#General configuration
[general]

	[general.bot]
		#Discord Bot Token
		token = ""

#Channel configurations
[[channels]]
	id = 242318118340805120
	dimensions = [0]

	[channels.messages]
		started = "Server started! (took {DURATION}s) :ok_hand:"

[[channels]]
	id = 262311018300915141
	dimensions = [-1, 1]

	[channels.messages]
		started = "Server started! (@ {TIME|hh:mma}) :ok_hand:"

