
#General configuration
[general]

	[general.bot]
		#Discord Bot Token
		token = ""

#Channel configurations
[[channels]]
	id = 242318118340805120
	dimensions = [0]

	[channels.messages]
		join = "Player joined."

[[channels]]
	id = 262311018300915141
	dimensions = [-1, 1]

	[channels.messages]
		stopped = "Server stopped."
		started = "Server started!"

