modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Axieum/MDC/issues"

[[mods]]
modId="mdc"
version="${file.jarVersion}"
displayName="Minecraft Discord Chat"
displayURL="https://github.com/Axieum/MDC"
logoFile="logo.png"
authors="Axieum"
description='''
Unify the Minecraft <-> Discord chat.
'''

[[dependencies.mdc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="SERVER"
